### ISSUE TITLE
Collections filter using single-valued Solr field

### ISSUE THREAD

**Issue by jordandukart** [jhu-idc/idc-ui-theme#44]
Given a object which has multiple `field_is_member_of` relationships only the first relationship is queried while using the advanced search component. 

This is due to using the single valued field `its_field_member_of` as opposed to its multi-valued counterpart `itm_field_member_of`.

Updating occurrences in https://github.com/jhu-idc/idc-ui-theme/blob/develop/js/packages/glimmer-idc/src/utils/results.ts should fix that.

Below showing Solr documents for some example objects:

<img width="955" alt="Screen Shot 2021-06-15 at 2 35 06 PM" src="https://user-images.githubusercontent.com/1337738/122098208-ee5a4e80-cde6-11eb-8559-6f70124271e7.png">

**Comment by jabrah** [comment]
Agreed that we should make this change. Seems simple enough that I should be able to include it in my next PR which will have a few small theme related updates
