### ISSUE TITLE
Search results are cached for anonymous users

### ISSUE THREAD

**Issue by jordandukart** [jhu-idc/idc-ui-theme#49]
As found by @jabrah in Slack when a content entity (node) has CRUD done to it the search results for the anonymous user is cached. 

To reproduce:

- Browse to `/collections` in a private window as anonymous and separately as a logged in user such that Drupal caches the results.
- Create a new collection.
- Refresh the `collections` route. Note how the anonymous user does not get the new result reflected while the logged in user does.
- Clear the Drupal cache (`drush cr`), refresh once again and now see the anonymous user has the correct results.

Corresponding issues are linked in the PR for further reading. It's also very easy to enable debugging of Drupal's cache in the headers of HTTP requests. If there's an interest on how to do this can give an overview in an impromptu break-out or some such.

**Comment by jordandukart** [comment]
Resolved in https://github.com/jhu-idc/idc_ui_module/pull/20.

**Comment by jaredgalanis** [comment]
Closed by https://github.com/jhu-idc/idc_ui_module/pull/20
